#define PROGRAM           101
#define DECLARE           102
#define IF                103
#define ELSE              104
#define WHILE             105
#define DOUBLEWHILE       106
#define LOOP              107
#define EXIT              108
#define FORCASE           109
#define INCASE            110
#define WHEN              111
#define DEFAULT           112
#define NOT               113
#define AND               114
#define OR                115
#define FUNCTION          116
#define PROCEDURE         117
#define CALL              118
#define RETURN            119
#define IN                120
#define INOUT             121
#define INPUT             122
#define PRINT             123
#define IDENTIFIER        124
#define PLUS              125
#define MINUS             126
#define STAR              127
#define DIV               128
#define LT                129
#define GT                130
#define EQUAL             131
#define L_EQ_THAN         132
#define G_EQ_THAN         133
#define NEQUAL            134
#define EXACT             135
#define LPAREN            136
#define RPAREN            137
#define LSQUARE_BRACK     138
#define RSQUARE_BRACK     139
#define LBRACK            140
#define RBRACK            141
#define SEMICOLON         142
#define COMMA             143
#define COLON             144
#define ENDL              145
#define DEC_CONST         146
#define STRING_LITERAL    147
